### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by Mekhi-M** [egage-proj/4-0-0-egage-Punchline#6]
- [x] The project is created using Vite
- [x] The code exists in more than one JS file
- [x] The project is deployed via GitHub Pages properly
- [x] CSS flexbox or grid was used
- [x] The code does not render unescaped text directly to the DOM (createElement or other escape method used)
